Update

diff --git a/api b/api
--- a/api
+++ b/api
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-DIRECTORY="$(dirname "$(readlink -f "$0")")"
+[ "$DIRECTORY" ] || DIRECTORY="$(dirname "$(readlink -f "$0")")"
 
 #text formatting variables
 RED="\e[31m"
@@ -84,8 +84,36 @@ get_pi_version() {
 	else
 		error "Raspberry Pi version not detected.\nIf you are using a Raspberry Pi 1, 2, 3 or 4, PLEASE report to https://github.com/cycool29/pi-tools/issue."
 	fi
+	[ "${NOT_SOURCED}" == 1 ] && echo "${PI_VERSION}"
 }
 
-if ! (return 0 2>/dev/null); then
-	echo wow
+get_codename() {
+    lsb_release -sc
+}
+
+trap "error 'Exiting now.'" INT
+
+sudo_password
+while read -r i; do
+	if ! dpkg -s "$i" &>/dev/null ; then
+		PACKAGE_TO_INSTALL+="$i "
+	fi
+done <"${DIRECTORY}/files/dependencies"
+
+[ "${PACKAGE_TO_INSTALL}" != '' ] && status_bold "Installing required dependencies" && (OUTPUT="$(sudo apt-get update 2>&1 && sudo apt-get install ${PACKAGE_TO_INSTALL} 2>&1)" || error "Failed to install required dependencies.\nError:\n${OUTPUT}")
+
+if ! ping -q -c1 example.com &>/dev/null; then
+	status "No internet connection (failed to ping example.com), running in no internet mode..."
+	NO_INTERNET=1
+fi
+
+chmod +x "${DIRECTORY}/scripts/*" &>/dev/null
+
+if ! (return 0 &>/dev/null); then
+	if [ "$@" ]; then
+		export NOT_SOURCED=1 #remember not sourced 
+		"$@"
+	else
+		error "No argument was given."
+	fi
 fi
diff --git a/pi-tools b/pi-tools
--- a/pi-tools
+++ b/pi-tools
@@ -1,6 +1,9 @@
 #!/bin/bash
 # shellcheck disable=SC2155,SC2094,SC2034,SC2059
 
+export DIRECTORY="$(dirname "$(readlink -f "$0")")"
+source "${DIRECTORY}/api" || error "Failed to source api."
+
 update_apps() {
 	sudo_password
 	status_bold "Updating APT"
@@ -32,40 +35,13 @@ set_keyboard() {
 	success_bold "Done"
 }
 
-get_debian_version(){
-	DEBIAN_VERSION="$(cut -d . -f 1 < /etc/debian_version)" || error "Failed to retrieve Debian version number.\nPLEASE report to https://github.com/cycool29/pi-tools/issue if you are on Raspberry Pi."
-}
-
-trap "error 'Exiting now.'" INT
-
-sudo_password
-while read -r i; do
-	if [ "$(dpkg -l "$i" 2> /dev/null | tail -n 1 | cut -d ' ' -f 1)" != "ii" ]; then
-		PACKAGE_TO_INSTALL+="$i "
-	fi
-done <"${DIRECTORY}/dependencies"
-
-[ "${PACKAGE_TO_INSTALL}" != '' ] && status_bold "Installing required dependencies" && (OUTPUT="$(sudo apt-get update 2>&1 && sudo apt-get install "${PACKAGE_TO_INSTALL}" 2>&1)" || error "Failed to install required dependencies.\nError:\n${OUTPUT}")
-
-if ! ping -q -c1 example.com &>/dev/null; then
-	status "No internet connection (failed to ping example.com), running in no internet mode..."
-	NO_INTERNET=1
-fi
-get_pi_version
-get_device_info noprint
-get_debian_version
-
 case $1 in
 	-h|--help)
 		show_help_message
 	;;
 	d|device-info)
 		shift
-		if [ "$1" == "--noprint" ]; then
-			get_device_info noprint
-		else 
-			get_device_info
-		fi
+		"${DIRECTORY}/scripts/get-device-info" || exit 1
 	;;
 	u|update-apps)
 		shift
@@ -81,6 +57,6 @@ case $1 in
 	;;
 	*)
 		error "Option not recognized.\n" --no-exit
-		show_help_message
+		pi-tools_help_message
 esac
 #echo "$(echo "apt ($(apt list --installed  | grep -v Listing 2>/dev/null | wc -l))")$([ -a "$(command -v snap)" ] && if ! snap list 2>&1 | grep -q "No snaps are installed"; then echo " snap ($(snap list | tail -n +2 | wc -l))"; fi)$([ -a "$(command -v flatpak)" ] && if flatpak info 2>/dev/null | grep -q "Note that the directories"; then export XDG_DATA_DIRS="$XDG_DATA_DIRS:$(flatpak info 2>/dev/null | tail -n +4 | head -n 2 | xargs | sed 's/ /:/g')"; fi && [ "$(flatpak list)" != "" ] && echo " flatpak ($(flatpak list | grep -v "Application ID"  | wc -l))")"
diff --git a/scripts/expand-root-filesystem b/scripts/expand-root-filesystem
--- a/scripts/expand-root-filesystem
+++ b/scripts/expand-root-filesystem
@@ -1,11 +1,7 @@
 #!/bin/bash
 # shellcheck disable=SC2155,SC2094,SC2034,SC2059
 
-if ! pi-tools_help_message &>/dev/null; then
-	echo -e "\e[31m\e[1m[!]\e[0m \e[91mThis script cannot run without sourcing the pi-tools api script.\e[0m" 
-	echo -e "\e[31m\e[1m[!]\e[0m \e[91mPlease do not run this script standalone.\e[0m" 
-	exit 1
-fi
+source "${DIRECTORY}/api" || error "Failed to source api."
 
 sudo_password || exit 1
 ROOT_PARTITION="$(sudo findmnt / -o source -n)"
diff --git a/scripts/get-device-info b/scripts/get-device-info
--- a/scripts/get-device-info
+++ b/scripts/get-device-info
@@ -1,10 +1,6 @@
 #!/bin/bash
 
-if ! pi-tools_help_message &>/dev/null; then
-	echo -e "\e[31m\e[1m[!]\e[0m \e[91mThis script cannot run without sourcing the pi-tools api script.\e[0m" 
-	echo -e "\e[31m\e[1m[!]\e[0m \e[91mPlease do not run this script standalone.\e[0m" 
-	exit 1
-fi
+source "${DIRECTORY}/api" || error "Failed to source api."
 
 OS="$(grep PRETTY_NAME  < /etc/os-release | tr -d '"' | awk -F= '{print $2}')" 
 OS_ARCH="$(dpkg --print-architecture)" 
@@ -26,24 +22,20 @@ CURRENT_USER="$(whoami)"
 SOC_VERSION="$(grep Hardware < /proc/cpuinfo | cut -c12-18)"
 GPU_TEMPERATURE="$(sed s/temp=//g <<< $(vcgencmd measure_temp))"
 
-if echo "$@" | grep -q noprint; then
-	true
-else
-	echo -e "${GREEN}Operating system   ${NORMAL} : $(if [ "${OS}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OS}"; fi)"
-	echo -e "${GREEN}OS Architecture    ${NORMAL} : $(if [ "${OS_ARCH}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OS_ARCH}"; fi)"
-	echo -e "${GREEN}Kernel             ${NORMAL} : $(if [ "${KERNEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${KERNEL}"; fi)"
-	echo -e "${GREEN}Raspberry Pi Model ${NORMAL} : $(if [ "${MODEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${MODEL}"; fi)"
-	echo -e "${GREEN}RAM Size           ${NORMAL} : $(if [ "${RAM_SIZE}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${RAM_SIZE}"; fi)"
-	echo -e "${GREEN}Image Version      ${NORMAL} : $(if [ "${IMAGE_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${IMAGE_VERSION}"; fi)"
-	echo -e "${GREEN}Installed Packages ${NORMAL} : $(if [ "${INSTALLED_PACKAGES}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${INSTALLED_PACKAGES}"; fi)"
-	echo -e "${GREEN}Uptime             ${NORMAL} : $(if [ "${UPTIME}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${UPTIME}"; fi)"
-	echo -e "${GREEN}Resolution         ${NORMAL} : $(if [ "${RESOLUTION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${RESOLUTION}"; fi)"
-	echo -e "${GREEN}Desktop Environment${NORMAL} : $(if [ "${DESKTOP_ENVIRONMENT}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${DESKTOP_ENVIRONMENT}"; fi)"
-	echo -e "${GREEN}Window Manager     ${NORMAL} : $(if [ "${WINDOW_MANAGER}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${WINDOW_MANAGER}"; fi)"
-	echo -e "${GREEN}OpenGL Version     ${NORMAL} : $(if [ "${OPENGL_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OPENGL_VERSION}"; fi)"
-	echo -e "${GREEN}GPU Model          ${NORMAL} : $(if [ "${GPU_MODEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${GPU_MODEL}"; fi)"
-	echo -e "${GREEN}Local IP Address   ${NORMAL} : $(if [ "${LOCAL_IP}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${LOCAL_IP}"; fi)"
-	echo -e "${GREEN}Public IP Address  ${NORMAL} : $(if [ "${PUBLIC_IP}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${PUBLIC_IP}"; fi)"
-	echo -e "${GREEN}Current User       ${NORMAL} : $(if [ "${CURRENT_USER}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${CURRENT_USER}"; fi)"
-	echo -e "${GREEN}SoC Version        ${NORMAL} : $(if [ "${SOC_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${SOC_VERSION}"; fi)"
-fi
+echo -e "${GREEN}Operating system   ${NORMAL} : $(if [ "${OS}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OS}"; fi)"
+echo -e "${GREEN}OS Architecture    ${NORMAL} : $(if [ "${OS_ARCH}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OS_ARCH}"; fi)"
+echo -e "${GREEN}Kernel             ${NORMAL} : $(if [ "${KERNEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${KERNEL}"; fi)"
+echo -e "${GREEN}Raspberry Pi Model ${NORMAL} : $(if [ "${MODEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${MODEL}"; fi)"
+echo -e "${GREEN}RAM Size           ${NORMAL} : $(if [ "${RAM_SIZE}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${RAM_SIZE}"; fi)"
+echo -e "${GREEN}Image Version      ${NORMAL} : $(if [ "${IMAGE_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${IMAGE_VERSION}"; fi)"
+echo -e "${GREEN}Installed Packages ${NORMAL} : $(if [ "${INSTALLED_PACKAGES}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${INSTALLED_PACKAGES}"; fi)"
+echo -e "${GREEN}Uptime             ${NORMAL} : $(if [ "${UPTIME}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${UPTIME}"; fi)"
+echo -e "${GREEN}Resolution         ${NORMAL} : $(if [ "${RESOLUTION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${RESOLUTION}"; fi)"
+echo -e "${GREEN}Desktop Environment${NORMAL} : $(if [ "${DESKTOP_ENVIRONMENT}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${DESKTOP_ENVIRONMENT}"; fi)"
+echo -e "${GREEN}Window Manager     ${NORMAL} : $(if [ "${WINDOW_MANAGER}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${WINDOW_MANAGER}"; fi)"
+echo -e "${GREEN}OpenGL Version     ${NORMAL} : $(if [ "${OPENGL_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OPENGL_VERSION}"; fi)"
+echo -e "${GREEN}GPU Model          ${NORMAL} : $(if [ "${GPU_MODEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${GPU_MODEL}"; fi)"
+echo -e "${GREEN}Local IP Address   ${NORMAL} : $(if [ "${LOCAL_IP}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${LOCAL_IP}"; fi)"
+echo -e "${GREEN}Public IP Address  ${NORMAL} : $(if [ "${PUBLIC_IP}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${PUBLIC_IP}"; fi)"
+echo -e "${GREEN}Current User       ${NORMAL} : $(if [ "${CURRENT_USER}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${CURRENT_USER}"; fi)"
+echo -e "${GREEN}SoC Version        ${NORMAL} : $(if [ "${SOC_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${SOC_VERSION}"; fi)"
