Make scripts into functions

diff --git a/pi-tools b/pi-tools
--- a/pi-tools
+++ b/pi-tools
@@ -1,10 +1,216 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # shellcheck disable=SC2155,SC2094,SC2034,SC2059
 
 export DIRECTORY="$(dirname "$(readlink -f "$0")")"
-set -a 
-source "${DIRECTORY}/api" || error "Failed to source api."
-set +a
+
+#text formatting variables
+RED="\e[31m"
+GREEN="\e[32m"
+YELLOW="\e[33m"
+BLUE="\e[34m"
+CYAN="\e[36m"
+LIGHT_RED="\e[91m"
+LIGHT_GREEN="\e[92m"
+LIGHT_YELLOW="\e[93m"
+LIGHT_BLUE="\e[94m"
+LIGHT_CYAN="\e[96m"
+WHITE="\e[97m"
+DARK_GREY="\e[90m"
+BOLD="\e[1m"
+UNDERLINE="\e[4m"
+INVERTED="\e[7m"
+NORMAL="\e[0m"
+DIM="\e[2m"
+
+error() {
+	LINE_NUMBER=$1
+	ERROR_CODE=$2
+
+	echo -e "\n\e[91m[!] An error occured in $(realpath "$(readlink -f "$0")"):\e[0m\n" 1>&2
+
+	echo -e "\e[93m[!] LINE: ${LINE_NUMBER} \e[0m" 1>&2
+	echo -e "\e[93m[!] ERROR CODE: ${ERROR_CODE}\e[0m" 1>&2 
+
+
+	echo -e "\n\e[91m[!] Exiting now.\e[0m\n" 1>&2
+}
+
+question() {
+	echo -e "${YELLOW}${BOLD}[?]${NORMAL} ${LIGHT_YELLOW}$1${NORMAL}" 
+}
+
+status() { 
+	echo -e "${CYAN}${BOLD}[-]${NORMAL} ${LIGHT_CYAN}$1${NORMAL}" 
+}
+
+status_bold() { 
+	echo -e "${CYAN}${BOLD}[-]${NORMAL} ${LIGHT_CYAN}${BOLD}$1${NORMAL}" 
+}
+
+success() { 
+	echo -e "${GREEN}${BOLD}[✔]${NORMAL} ${LIGHT_GREEN}$1${NORMAL}" 
+}
+
+success_bold() {
+	echo -e "${GREEN}${BOLD}[✔]${NORMAL} ${LIGHT_GREEN}${BOLD}$1${NORMAL}"
+}
+
+pi-tools_help_message() {
+	echo "╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╭╮
+╱╱╱╱╱╱╭╯╰╮╱╱╱╱╱┃┃
+╭━━┳╮╱╰╮╭╋━━┳━━┫┃╭━━╮
+┃╭╮┣╋━━┫┃┃╭╮┃╭╮┃┃┃━━┫
+┃╰╯┃┣━━┫╰┫╰╯┃╰╯┃╰╋━━┃
+┃╭━┻╯╱╱╰━┻━━┻━━┻━┻━━╯
+┃┃
+╰╯"
+	echo "pi-tools (pt) 1.0 on Raspberry Pi ${PI_VERSION}, $(dpkg --print-architecture)"
+	echo "Installed at ${DIRECTORY}."
+	echo
+	echo "pi-tools is a command-line tool to access almost all settings, functions, etc, of your Raspberry Pi."
+   
+}
+
+is_empty() {
+    local TARGET="${1}"
+
+    [[ -z "${TARGET}" ]]
+}
+
+is_not_empty() {
+    local TARGET="${1}"
+
+    [[ -n "${TARGET}" ]]
+}
+
+is_file() {
+    local TARGET="${1}"
+
+    [[ -f "${TARGET}" ]]
+}
+
+is_dir() {
+    local TARGET="${1}"
+
+    [[ -d "${TARGET}" ]]
+}
+
+sudo_password() {
+	if ! sudo -n ls &>/dev/null; then 
+		status "This operation needs root access."
+		sudo -S true || error "Authentication Failed." 
+		success "Root authentication success."
+	fi
+}
+
+get_pi_version() {
+	if grep -q "^Revision\s*:\s*00[0-9a-fA-F][0-9a-fA-F]$" /proc/cpuinfo || grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[0-36][0-9a-fA-F]$" /proc/cpuinfo ; then
+		PI_VERSION=1
+	elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]04[0-9a-fA-F]$" /proc/cpuinfo; then
+		PI_VERSION=2
+	elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[9cC][0-9a-fA-F]$" /proc/cpuinfo; then
+		PI_VERSION=3
+	elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F]3[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$" /proc/cpuinfo; then
+		PI_VERSION=4
+	else
+		error "Raspberry Pi version not detected.\nIf you are using a Raspberry Pi 1, 2, 3 or 4, PLEASE report to https://github.com/cycool29/pi-tools/issue."
+	fi
+	[ "${NOT_SOURCED}" == 1 ] && echo "${PI_VERSION}"
+}
+
+get_codename() {
+    lsb_release -sc
+}
+
+check_internet() {
+	ping -q -c1 example.com &>/dev/null 
+	return $?
+}
+
+install_pi-tools_dependencies() {
+	sudo_password || exit 1
+	# shellcheck disable=2046
+	(sudo apt-get update --allow-releaseinfo-change 2>&1 && sudo apt-get install -qq --no-install-recommends $(cat "${DIRECTORY}/files/dependencies")) || error "Failed to install pi-tools dependencies."
+}
+
+prepare() {
+	while read -r i; do
+		if ! dpkg -s "$i" &>/dev/null ; then
+			install_pi-tools_dependencies || exit 1
+			break
+		fi
+	done <"${DIRECTORY}/files/dependencies"
+
+	chmod +x "${DIRECTORY}"/scripts/*
+}
+
+
+scan_bluetooth() { # scan bluetooth devices, the only arg accepted is the timeout duration
+	TIMEOUT_DURATION="${1}"
+	bluetoothctl --timeout "${TIMEOUT_DURATION}" scan on
+}
+
+detect_device_type() {
+	TARGET="${1}"
+	if [[ "${TARGET}" =~ ^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$ ]]; then
+		echo "MAC Address"
+	else 
+		echo "Device Name" 
+	fi
+}
+
+turn_bluetooth() {
+	case ${1} in 
+		on)
+			status "Turning on Bluetooth..."
+			sudo_password || exit 1
+			sudo rfkill unblock bluetooth || error "Failed to turn on Bluetooth."
+			sudo service bluetooth restart 
+			bluetoothctl power on
+		;;
+		off)
+			status "Turning off Bluetooth..."
+			sudo_password || exit 1
+			sudo rfkill block bluetooth || error "Failed to turn off Bluetooth."
+		;;
+		restart)
+			status "Restarting Bluetooth"
+			sudo_password || exit 1
+			sudo rfkill block bluetooth || error "Failed to turn off Bluetooth."
+			sudo rfkill unblock bluetooth || error "Failed to turn on Bluetooth."
+		;;
+	esac
+}
+
+find_root_partition() {
+	sudo findmnt / -o source -n
+}
+
+find_root_device(){
+	local ROOT_PARTITION="${1}"
+	echo "/dev/$(sudo lsblk -no pkname "${ROOT_PARTITION}")"
+}
+
+find_root_partition_number() {
+	local ROOT_PARTITION="${1}"
+	grep -o "[[:digit:]]*$" <<<"${ROOT_PARTITION}"
+}
+
+find_last_root_partition_number(){
+	local ROOT_DEVICE="${1}"
+	sudo parted "${ROOT_DEVICE}" -ms unit s p | tail -n 1 | cut -f 1 -d:
+}
+
+find_partition_start_offset(){
+	local ROOT_DEVICE="${1}"
+	local PARTITION_NUMBER="${2}"
+	local PARTITION_START="$(sudo parted "${ROOT_DEVICE}" -ms unit s p | grep "^${PARTITION_NUMBER}" | cut -f 2 -d: | sed 's/[^0-9]//g')"
+	if is_empty "${PARTITION_START}"; then
+		return 1
+	else
+		echo "${PARTITION_START}"
+	fi
+}
 
 update_apps() {
 	sudo_password
@@ -37,36 +243,95 @@ set_keyboard() {
 	success_bold "Done"
 }
 
-case $1 in
-	-h|--help)
-		show_help_message
-	;;
-	d|device-info)
-		shift
-		"${DIRECTORY}/scripts/get-device-info" || exit 1
-	;;
-	bt|bluetooth)
-		shift
-		"${DIRECTORY}/scripts/bluetooth" "$@" || exit 1
-	;;
-	u|update-apps)
-		shift
-		update_apps
-	;;
-	sk|set-keyboard)
-		shift
-		set_keyboard
-	;;
-	ef|expand-filesystem)
-		shift
-		expand_rootfs
-	;;
-	wf|wifi)
-		shift
-		"${DIRECTORY}/scripts/wifi" "$@" || exit 1
-	;;
-	*)
-		error "Option not recognized.\n" --no-exit
-		pi-tools_help_message
-esac
+get_device_info(){
+
+	DPKG_PACKAGES="$(dpkg --get-selections | grep -vc deinstall)"
+
+	command -v snap &>/dev/null && ! snap list 2>&1 \
+		| grep -q "No snaps are installed" \
+		&& SNAP_PACKAGES="$(snap list | tail -n +2 | wc -l)"
+
+	command -v flatpak &>/dev/null \
+		&& if flatpak info 2>/dev/null | grep -q "Note that the directories"; then 
+			export XDG_DATA_DIRS="$XDG_DATA_DIRS:$(flatpak info 2>/dev/null | tail -n +4 | head -n 2 | xargs | sed 's/ /:/g')"
+		fi && [ "$(flatpak list)" != "" ] && FLATPAK_PACKAGES="$(flatpak list | grep -vc 'Application ID')"
+	
+	OS="$(grep PRETTY_NAME  < /etc/os-release | tr -d '"' | awk -F= '{print $2}')" 
+	OS_ARCH="$(dpkg --print-architecture)" 
+	KERNEL="$(uname -mrs)" 
+	MODEL="$(grep Model  < /proc/cpuinfo | xargs | sed 's/Model : //g')" 
+	RAM_SIZE="$(echo "scale=2 ; $( awk '/MemTotal/ {print $2}' /proc/meminfo ) / 1024000 " | bc ) GB"
+	IMAGE_VERSION="$(grep 'Raspberry Pi reference'  < /etc/rpi-issue | sed 's/Raspberry Pi reference //g')" 
+	INSTALLED_PACKAGES="dpkg (${DPKG_PACKAGES})$(is_not_empty "${SNAP_PACKAGES}" && echo ", snap (${SNAP_PACKAGES})")$(is_not_empty "${FLATPAK_PACKAGES}" && echo ", flatpak (${FLATPAK_PACKAGES})")"
+	UPTIME="$(uptime -p | sed "s/up //g" | sed s/,//g)" 
+	RESOLUTION="$(fbset -i  | grep "mode " | tr -d '"' | tr -d "mode ")" 
+	DESKTOP_ENVIRONMENT="$XDG_CURRENT_DESKTOP" 
+	WINDOW_MANAGER="$(xprop -id "$(xprop -root -notype _NET_SUPPORTING_WM_CHECK | sed 's/.*# //')" -notype -len 100 -f _NET_WM_NAME 8t | grep WM_NAME | sed 's/.*= //g' | xargs)" 
+	OPENGL_VERSION="$(glxinfo -B | grep 'OpenGL ES profile version string' | sed 's/OpenGL ES profile version string: //g')"
+	GPU_MODEL="$(glxinfo -B | grep 'Device\|Vendor' | sed 's/.*Device: //g' | sed 's/.*Vendor: //g' | sed -e 's/([^()]*)//g' | xargs)"
+	HOSTNAME="$(hostname)"
+	LOCAL_IP="$(hostname -I | awk '{print $1}')"
+	PUBLIC_IP="$(wget -qO- ifconfig.me)"
+	CURRENT_USER="$(whoami)"
+	SOC_VERSION="$(grep Hardware < /proc/cpuinfo | cut -c12-18)"
+	# shellcheck disable=SC2001
+	GPU_TEMPERATURE="$(sed s/temp=//g <<< "$(vcgencmd measure_temp)")"
+
+	echo -e "${GREEN}Operating system   ${NORMAL} : $(if [ "${OS}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OS}"; fi)"
+	echo -e "${GREEN}OS Architecture    ${NORMAL} : $(if [ "${OS_ARCH}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OS_ARCH}"; fi)"
+	echo -e "${GREEN}Kernel             ${NORMAL} : $(if [ "${KERNEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${KERNEL}"; fi)"
+	echo -e "${GREEN}Raspberry Pi Model ${NORMAL} : $(if [ "${MODEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${MODEL}"; fi)"
+	echo -e "${GREEN}RAM Size           ${NORMAL} : $(if [ "${RAM_SIZE}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${RAM_SIZE}"; fi)"
+	echo -e "${GREEN}Image Version      ${NORMAL} : $(if [ "${IMAGE_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${IMAGE_VERSION}"; fi)"
+	echo -e "${GREEN}Installed Packages ${NORMAL} : $(if [ "${INSTALLED_PACKAGES}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${INSTALLED_PACKAGES}"; fi)"
+	echo -e "${GREEN}Uptime             ${NORMAL} : $(if [ "${UPTIME}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${UPTIME}"; fi)"
+	echo -e "${GREEN}Resolution         ${NORMAL} : $(if [ "${RESOLUTION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${RESOLUTION}"; fi)"
+	echo -e "${GREEN}Desktop Environment${NORMAL} : $(if [ "${DESKTOP_ENVIRONMENT}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${DESKTOP_ENVIRONMENT}"; fi)"
+	echo -e "${GREEN}Window Manager     ${NORMAL} : $(if [ "${WINDOW_MANAGER}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${WINDOW_MANAGER}"; fi)"
+	echo -e "${GREEN}OpenGL Version     ${NORMAL} : $(if [ "${OPENGL_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${OPENGL_VERSION}"; fi)"
+	echo -e "${GREEN}GPU Model          ${NORMAL} : $(if [ "${GPU_MODEL}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${GPU_MODEL}"; fi)"
+	echo -e "${GREEN}Local IP Address   ${NORMAL} : $(if [ "${LOCAL_IP}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${LOCAL_IP}"; fi)"
+	echo -e "${GREEN}Public IP Address  ${NORMAL} : $(if [ "${PUBLIC_IP}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${PUBLIC_IP}"; fi)"
+	echo -e "${GREEN}Current User       ${NORMAL} : $(if [ "${CURRENT_USER}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${CURRENT_USER}"; fi)"
+	echo -e "${GREEN}SoC Version        ${NORMAL} : $(if [ "${SOC_VERSION}" == "" ]; then echo -e "${DARK_GREY}Not available${NORMAL}"; else echo "${SOC_VERSION}"; fi)"	
+}
+
+trap 'error $LINENO $?' ERR
+
+testfunc() {
+	lalalal
+}
+
+testfunc
+# case $1 in
+# 	-h|--help)
+# 		show_help_message
+# 	;;
+# 	di|device-info)
+# 		shift
+# 		"${DIRECTORY}/scripts/get-device-info" || exit 1
+# 	;;
+# 	bt|bluetooth)
+# 		shift
+# 		"${DIRECTORY}/scripts/bluetooth" "$@" || exit 1
+# 	;;
+# 	u|update-apps)
+# 		shift
+# 		update_apps
+# 	;;
+# 	sk|set-keyboard)
+# 		shift
+# 		set_keyboard
+# 	;;
+# 	ef|expand-filesystem)
+# 		shift
+# 		expand_rootfs
+# 	;;
+# 	wf|wifi)
+# 		shift
+# 		"${DIRECTORY}/scripts/wifi" "$@" || exit 1
+# 	;;
+# 	*)
+# 		pi-tools_help_message
+# esac
 #echo "$(echo "apt ($(apt list --installed  | grep -v Listing 2>/dev/null | wc -l))")$([ -a "$(command -v snap)" ] && if ! snap list 2>&1 | grep -q "No snaps are installed"; then echo " snap ($(snap list | tail -n +2 | wc -l))"; fi)$([ -a "$(command -v flatpak)" ] && if flatpak info 2>/dev/null | grep -q "Note that the directories"; then export XDG_DATA_DIRS="$XDG_DATA_DIRS:$(flatpak info 2>/dev/null | tail -n +4 | head -n 2 | xargs | sed 's/ /:/g')"; fi && [ "$(flatpak list)" != "" ] && echo " flatpak ($(flatpak list | grep -v "Application ID"  | wc -l))")"
