Add set_keyboard

diff --git a/pi-tools b/pi-tools
--- a/pi-tools
+++ b/pi-tools
@@ -1,15 +1,17 @@
 #!/bin/bash
 
+DIRECTORY="$(readlink -f "$(dirname "$0")")"
+
 #text formatting variables
 RED="\e[31m"
 GREEN="\e[32m"
 YELLOW="\e[33m"
 BLUE="\e[34m"
+CYAN="\e[36m"
 LIGHT_RED="\e[91m"
 LIGHT_GREEN="\e[92m"
 LIGHT_YELLOW="\e[93m"
 LIGHT_BLUE="\e[94m"
-CYAN="\e[36m"
 LIGHT_CYAN="\e[96m"
 WHITE="\e[97m"
 DARK_GREY="\e[90m"
@@ -41,7 +43,8 @@ success() {
 }
 
 show_help_message() {
-	echo -e "pi-tools (pt) 1.0 in $(dpkg --print-architecture)"
+	echo "pi-tools (pt) 1.0 in $(dpkg --print-architecture)"
+	echo "Installed at ${DIRECTORY}."
 	echo "pi-tools is a command-line tool to access almost all settings, functions, etc, of your Raspberry Pi."
    
 }
@@ -85,6 +88,20 @@ sudo_password() {
 	fi
 }
 
+detect_pi_version() {
+	if grep -q "^Revision\s*:\s*00[0-9a-fA-F][0-9a-fA-F]$" /proc/cpuinfo || grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[0-36][0-9a-fA-F]$" /proc/cpuinfo ; then
+		PI_VERSION=1
+	elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]04[0-9a-fA-F]$" /proc/cpuinfo; then
+		PI_VERSION=2
+	elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[9cC][0-9a-fA-F]$" /proc/cpuinfo; then
+		PI_VERSION=3
+	elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F]3[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$" /proc/cpuinfo; then
+		PI_VERSION=4
+	else
+		error "Raspberry Pi version not detected.\nIf you are using a Raspberry Pi 1, 2, 3 or 4, PLEASE report to https://github.com/cycool29/pi-tools/issue."
+	fi
+}
+
 update_apps() {
 	sudo_password
 	status_bold "Updating APT"
@@ -100,7 +117,22 @@ update_apps() {
 	fi
 }
 
+set_keyboard() {
+	status_bold "Configuring keyboard"
+	sudo_password
+	status "Please select the keymap of the keyboard."
+	sudo -E sed -i /etc/default/keyboard -e "s/^XKBLAYOUT.*/XKBLAYOUT=\"$(grep "$(cut -c23- < "${DIRECTORY}/keymaps" | fzf --height 20 --cycle)" < "${DIRECTORY}/keymaps" | cut -c1-22 | xargs)\"/"
+	status "Configuring keyboard-configuration..."
+	OUTPUT="$(sudo -E dpkg-reconfigure -f noninteractive keyboard-configuration 2>&1)" || error "Failed to configure keyboard-configuration.\nError:\n${OUTPUT}"
+	status "Enabling keyboard-setup initscript..."
+	OUTPUT="$(sudo -E invoke-rc.d keyboard-setup start)" || error "Failed to enable keyboard-setup initscript.\nError:\n${OUTPUT}"
+	status "Setting up keyboard..."
+	sudo -E setsid sh -c 'exec setupcon -k --force <> /dev/tty1 >&0 2>&1'
+	sudo -E udevadm trigger --subsystem-match=input --action=change
+}
 
+sudo_password
+detect_pi_version
 
 case $1 in
 	-h|--help)
@@ -117,6 +149,10 @@ case $1 in
 	-u|--update)
 		shift
 		update_apps
+	;;
+	set-keyboard)
+		shift
+		set_keyboard
 	;;
 esac
 #echo "$(echo "apt ($(apt list --installed  | grep -v Listing 2>/dev/null | wc -l))")$([ -a "$(command -v snap)" ] && if ! snap list 2>&1 | grep -q "No snaps are installed"; then echo " snap ($(snap list | tail -n +2 | wc -l))"; fi)$([ -a "$(command -v flatpak)" ] && if flatpak info 2>/dev/null | grep -q "Note that the directories"; then export XDG_DATA_DIRS="$XDG_DATA_DIRS:$(flatpak info 2>/dev/null | tail -n +4 | head -n 2 | xargs | sed 's/ /:/g')"; fi && [ "$(flatpak list)" != "" ] && echo " flatpak ($(flatpak list | grep -v "Application ID"  | wc -l))")"
