Update

diff --git a/scripts/bluetooth b/scripts/bluetooth
--- a/scripts/bluetooth
+++ b/scripts/bluetooth
@@ -27,20 +27,20 @@ case "$1" in
 		grep -q -- '--pair-only' <(echo "$@") && PAIR_ONLY=1
 		
 		status "Scanning available devices..."
-		bluetoothctl --timeout 15 scan on || error "Failed to scan available devices."
-			
+		BLUETOOTH_SCAN_RESULT="$(bluetoothctl --timeout 15 scan on)" || error "Failed to scan available devices."
+		status_green "Scan result:"
+		echo "${BLUETOOTH_SCAN_RESULT}"
 		
 		if [[ "$(echo "${DEVICE}" | tr '[:lower:]' '[:upper:]')" =~ ^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$ ]]; then #given mac address
 			DEVICE="$(echo "${DEVICE}" |  tr '[:lower:]' '[:upper:]')"
 			status "Given MAC Address: ${DEVICE}"
+			
+		fi
 			status_bold "Connecting to ${DEVICE}"
 			turn_bluetooth on || exit 1
 			status "Powering on Bluetooth controller..."
-			bluetoothctl power off; bluetoothctl power on || error "Failed to power on Bluetooth controller."
-			if grep -q "${DEVICE}" <(bluetoothctl paired-devices); then 
-				success "${DEVICE} already paired."
-				[ "${PAIR_ONLY}" == 1 ] && exit 0
-			fi
-		fi
+			bluetoothctl power on || error "Failed to power on Bluetooth controller."
+			
 	;;
 esac
+
